INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Maria Brown', 'maria@gmail.com', '44691451811', 1, 2, 'RG', 'N/D', '', '', '2025-06-30', '2001-07-25', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Alex Green', 'alex@gmail.com', '44691451812', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Abel', 'abel@gmail.com', '15403518827', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Abraao Reis', 'abraao@gmail.com', '15692470721', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'ABRAAO TESTE DUPLICIDADE', 'abraao@gmail.com', '85642104012', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Adann', 'adann@gmail.com', '11362533866', 0, 1, 'RG', 'N/D', '', '+5511988921685', '2025-06-30', '1987-12-13', true, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Adriano Guerini Gadelha', 'adriano@gmail.com', '55290273778', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'AFONSO CELSO DE BARROS JUNIOR', 'afonso@gmail.com', '09446955742', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Alexandre Anthony Rafael Rezende', 'alexandre@gmail.com', '93533037029', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Alfa Teste', 'alfa@gmail.com', '04202795040', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Aline Cardoso', 'aline@gmail.com', '48544219837', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Allan', 'allan@gmail.com', '64823476069', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Maria Brown', 'maria1@gmail.com', '44691451821', 1, 2, 'RG', 'N/D', '', '', '2025-06-30', '2001-07-25', false, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Alex Green', 'alex1@gmail.com', '44691451813', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Abel', 'abel1@gmail.com', '15403518828', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Abraao Reis', 'abraao1@gmail.com', '15692470722', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'ABRAAO TESTE DUPLICIDADE', 'abraao1@gmail.com', '85642104013', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Adann', 'adann1@gmail.com', '11362533867', 0, 1, 'RG', 'N/D', '', '+5511988921685', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Adriano Guerini Gadelha', 'adriano1@gmail.com', '55290273779', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'AFONSO CELSO DE BARROS JUNIOR', 'afonso1@gmail.com', '09446955743', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Alexandre Anthony Rafael Rezende', 'alexandre1@gmail.com', '93533037039', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Alfa Teste', 'alfa1@gmail.com', '04202795041', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, false);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Aline Cardoso', 'aline1@gmail.com', '48544219847', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', true, true);
INSERT INTO tb_participant (external_code, full_name, email, cpf, gender, marital_status, identification_document, observation, phone, cell_phone, validity_registered_form, birth_date, active, digital_signature) VALUES ('', 'Allan', 'allan1@gmail.com', '64823476079', 0, 1, 'RG', 'N/D', '', '', '2025-06-30', '1987-12-13', false, false);

INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Alessandro Bernardello', 'Alves Dias', 'São Bernardo do Campo', 'SP', 241, 'Sem complemento', '09851-050', 1);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Lucidalva da Silva', 'Jardim das Orquideas', 'São Bernardo do Campo', 'SP', 538, 'Sem complemento', '09854-520', 2);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Jacob Scopel', 'Jardim Santa Terezinha', 'São Bernardo do Campo', 'SP', 74, 'Sem complemento', '09857-070', 2);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Goiás', 'Graça', 'Brasília', 'DF', 339, 'Sem complemento', '28041-111', 3);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Pernambuco', 'Vila Mariana', 'Fortaleza', 'CE', 253, 'Sem complemento', '48914-235', 4);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Paraíba', 'Centro', 'Florianópolis', 'SC', 224, 'Sem complemento', '26266-323', 5);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Rio Grande', 'Meireles', 'Rio de Janeiro', 'RJ', 91, 'Sem complemento', '44407-949', 6);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Rio Grande', 'Boa Viagem', 'Belo Horizonte', 'MG', 53, 'Sem complemento', '28469-644', 7);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Itú', 'Ipanema', 'Salvador', 'BA', 24, 'Sem complemento', '20905-845', 8);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Estrada Velha', 'Barra Funda', 'Rio de Janeiro', 'RJ', 363, 'Sem complemento', '61576-879', 9);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Avenida Brasil', 'Ipanema', 'Belo Horizonte', 'MG', 244, 'Sem complemento', '43708-546', 10);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua das Rosas', 'Bela Vista', 'São Paulo', 'SP', 407, 'Sem complemento', '99973-749', 11);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua das Acácias', 'Copacabana', 'Curitiba', 'PR', 200, 'Sem complemento', '13773-521', 12);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Paraíba', 'Bela Vista', 'Belo Horizonte', 'MG', 379, 'Sem complemento', '50929-391', 13);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua XV de Novembro', 'Sion', 'Porto Alegre', 'RS', 391, 'Sem complemento', '44185-296', 14);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Amazonas', 'Copacabana', 'Curitiba', 'PR', 204, 'Sem complemento', '22013-112', 15);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Estrada Velha', 'Savassi', 'Fortaleza', 'CE', 21, 'Sem complemento', '60946-126', 16);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Amazonas', 'Boa Vista', 'Florianópolis', 'SC', 46, 'Sem complemento', '47098-925', 17);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Bahia', 'Graça', 'São Paulo', 'SP', 216, 'Sem complemento', '79414-627', 18);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Estrada Velha', 'Ipanema', 'Porto Alegre', 'RS', 447, 'Sem complemento', '31691-921', 19);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Ceará', 'Leblon', 'Salvador', 'BA', 405, 'Sem complemento', '24373-653', 20);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Avenida Paulista', 'Boa Viagem', 'Fortaleza', 'CE', 129, 'Sem complemento', '93271-580', 21);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Bahia', 'Sion', 'Recife', 'PE', 436, 'Sem complemento', '68667-684', 22);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua das Palmeiras', 'Boa Viagem', 'Porto Alegre', 'RS', 230, 'Sem complemento', '30403-246', 23);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Ceará', 'Mooca', 'Brasília', 'DF', 211, 'Sem complemento', '53330-812', 24);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Tiradentes', 'Jardim América', 'Porto Alegre', 'RS', 435, 'Sem complemento', '55505-457', 3);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Pernambuco', 'Graça', 'Salvador', 'BA', 63, 'Sem complemento', '11703-367', 4);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Vila Nova', 'Meireles', 'Rio de Janeiro', 'RJ', 282, 'Sem complemento', '39371-101', 2);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Tiradentes', 'Jardim Botânico', 'Belo Horizonte', 'MG', 129, 'Sem complemento', '12477-664', 9);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua XV de Novembro', 'Centro', 'Brasília', 'DF', 170, 'Sem complemento', '52291-235', 2);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua das Palmeiras', 'Leblon', 'Salvador', 'BA', 452, 'Sem complemento', '55417-754', 5);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua das Acácias', 'Meireles', 'Recife', 'PE', 494, 'Sem complemento', '32634-876', 5);
INSERT INTO tb_address (street, neighborhood, city, state, number, complement, zip_code, participant_id) VALUES ('Rua Mato Grosso', 'Floresta', 'Fortaleza', 'CE', 403, 'Sem complemento', '34343-872', 2);


INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('PIS', '150.21871.67-0', 1);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CNH', '83057176440', 1);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CNPJ', '81.799.671/0001-66', 2);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CPF', '359.482.716-04', 3);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RG', '12.345.678-9', 7);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CNH', '04768932514', 2);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('Passport', 'PA1234567', 5);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RNE', 'MZ9876543', 8);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('Carteira Trabalho', '123.456.7890-12', 4);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CPF', '781.905.332-88', 10);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RG', '98.765.432-1', 6);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CNH', '35910284763', 9);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('Passport', 'BR7654321', 3);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RNE', 'XP1230987', 11);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('Carteira Trabalho', '987.654.3210-00', 7);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CPF', '042.317.569-21', 5);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RG', '23.456.789-0', 4);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CNH', '82937465012', 6);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('Passport', 'PT2345678', 8);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RNE', 'AB7654321', 13);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('Carteira Trabalho', '456.123.7890-34', 14);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('CPF', '619.283.407-55', 15);
INSERT INTO tb_personal_document (document_type, document_number, participant_id) VALUES ('RG', '34.567.890-1', 16);

INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('5503 1101 2800 5301', 1);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('5425 4627 2006 9697', 2);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('3849 751666 3048', 2);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('4837 592314 7281', 1);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('1920 847563 1059', 3);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('7584 230198 4627', 5);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('6019 475820 3346', 21);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('3748 690251 8873', 4);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('8291 057634 1928', 6);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('5603 842719 4051', 7);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('2470 193856 7204', 8);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('9156 308472 1560', 9);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('1029 574806 3837', 10);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('7830 149265 9023', 11);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('4392 658710 2745', 20);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('6501 392048 6174', 13);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('5278 406193 8390', 4);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('3145 780629 4501', 15);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('8902 157364 2187', 6);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('2057 493810 5763', 7);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('6714 802359 1432', 8);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('3489 921740 6850', 9);
INSERT INTO tb_signature_card (card_number, participant_id) VALUES ('9603 517284 3096', 10);
